services:
  - type: web
    name: weather-dashboard
    env: node
    runtime: node
    nodeVersion: 18
    rootDir: ./server
    buildCommand: |
      cd ../client && npm install && npm run build
      mkdir -p client/dist && cp -r ../client/dist/* client/dist/
      npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
