services:
  - type: web
    name: weather-dashboard
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
    plan: free
    healthCheckPath: /
    maxShutdownDelaySeconds: 60