services:
  # Backend API service
  - type: web
    name: weather-dashboard-api
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
    
  # Frontend static site
  - type: web
    name: weather-dashboard-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
