services:
  # Backend API service and Frontend static site combined into a single web service
  - type: web
    name: weather-dashboard
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
