services:
  # Backend API service
  - type: web
    name: weather-dashboard-api
    env: node
    rootDir: ./server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
    
  # Frontend static site
  - type: web
    name: weather-dashboard-client
    env: static
    rootDir: ./client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
