services:
  - type: web
    name: weather-dashboard
    runtime: node
    rootDir: /opt/render/project/src
    buildCommand: |
      cd client && npm install && npm run build && \
      cd ../server && npm install && npm run build && \
      mkdir -p /opt/render/project/src/server/client/dist && \
      cp -r /opt/render/project/src/client/dist/* /opt/render/project/src/server/client/dist/
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
    plan: free
    healthCheckPath: /
    maxShutdownDelaySeconds: 60
